"""
You are implementing a file management feature that operates in a multi-user environment. The feature needs to manage temporary files generated by different processes. Your task is to develop a function `discard_temp_file` that checks if a temporary file exists and deletes it when found.
"""
def discard_temp_file(temp_file_to_discard):
    if not os.path.exists(temp_file_to_discard):
        return True
    try:
        os.remove(temp_file_to_discard)
        return True
    except OSError:
        print(f"Failed to delete {temp_file_to_discard}")
        return False
    return False