"""
You are implementing a file management feature that operates in a multi-user environment. The feature needs to manage temporary files generated by different processes. Your task is to develop a function `remove_tmp_file` that checks if a temporary file exists and deletes it when found.
"""
def remove_tmp_file(path_to_tmp_file):
    if not os.path.exists(path_to_tmp_file):
        return True
    try:
        os.remove(path_to_tmp_file)
        return True
    except OSError:
        print(f"Failed to delete {path_to_tmp_file}")
        return False
    return False